config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pft#index"
  
  get 'work', to: 'pft#work'
  get 'contact', to: 'pft#contact'
  get 'detail', to: 'pft#detail'
  get 'detail2', to: 'pft#detail2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pft.rb
class Pft < ApplicationRecord
  def change
    create_table :pft do |t|
      t.timestamps
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pft_controller.rb
class PftController < ApplicationController
  def index
  end

  def about
  end

  def work
  end

  def contact
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pft_helper.rb
module PftHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Portforio
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "/public/favicon.ico", :rel => "shortcut icon"}/
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.7.2/css/all.css", :integrity => "sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
    :css
      @import url('https://fonts.googleapis.com/css?family=Varela+Round&display=swap');
  %body
    = yield

app/views/pft/contact.html.haml
%ul.pf__nav
  %li.pf__nav__principle
    = link_to contact_path, class: "pf__nav__principle__text" do
      %i.far.fa-comments
      PROFILE
%ul.pf__nav
  %li.pf__nav__works
    = link_to work_path, class: "pf__nav__works__text" do
      %i.fas.fa-desktop
      WORKS
  %li.pf__nav__principle
    = link_to root_path, class: "pf__nav__principle__text" do
      %i.fas.fa-backward
      TOP
.contact
  .contact__wrap
    .contact__wrap__pic
      = image_tag "メイ.jpg", class: "pf__slider__create__img"
    %ul.contact__wrap__text
      %li.contact__wrap__text__top
        ウェブエンジニア teratti
      %li.contact__wrap__text__top
        2004年から新卒で15年勤めた運送会社を辞め
      %li.contact__wrap__text__top
        tech::expertの短期集中コースを受講 64期卒業
      %li.contact__wrap__text__top
        6人の子供を持つビッグダディ
      %li.contact__wrap__text__top
        事業内容： Ruby, Ruby on rails, HTML haml, CSS scss,
      %li.contact__wrap__text__top
        javascript, jquery, github, AWS, mysql 等の技術を用いた複合的機能の企画・実装
      %li.contact__wrap__text__top
        ーーーーーーーーーーーーーーーー
      %li.contact__wrap__text__top
        address:東京都 & 熊本県
      %li.contact__wrap__text__top
        contact:

app/views/pft/detail.html.haml
%ul.pf__nav
  %li.pf__nav__works
    .pf__nav__works__text
      %i.fas.fa-desktop
      DETAIL
%ul.pf__nav
  %li.pf__nav__works
    = link_to work_path, class: "pf__nav__works__text" do
      %i.fas.fa-desktop
      WORKS
  %li.pf__nav__principle
    = link_to contact_path, class: "pf__nav__principle__text" do
      %i.far.fa-comments
      PROFILE
.pic
  %ul.pic__slider
    %li.pic__slider__works
      =link_to "http://52.68.71.170/", class: ".pic__slider__works__path" do
        = image_tag 'free.png', height: '400px', width: '600px'
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-project-diagram
      プログラム（プロジェクト）名
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    free-market
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-list-ul
      プログラムの概要やビジュアル（UI）の紹介
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    ユーザー登録 商品の出品・購入 カード決済(テスト)
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-user-alt
      クライアント名
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    なし
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fab.fa-product-hunt
      製作時期と製作期間
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    2019/12/6 ~ 2019/12/26
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-bullseye
      プログラムの目的
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    サーバーサイド・フロントエンド・デプロイなどの一連の流れの理解。知識を深めるため
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-cube
      プログラムのコンセプト
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    なし
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.far.fa-comment-dots
      クライアントの要求事項や設計仕様
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    某商品購入サイトを一から全く同じように作ること
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fab.fa-github
      使用言語や仕様ソフト、開発環境の紹介
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    Ruby/ Rails/ haml/ scss/ js/ jquery/ mysql/ aws/
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-arrows-alt
      チームで作成した場合は自分の担当箇所やポジションの紹介
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    フロントエンド全て 商品の一覧表示 カード決済機能 ページ間の連動性
.listing-wrap
  = link_to "http://52.68.71.170/", class: "listing-wrap__link" do
    .listing-wrap__link__box
      .listing-wrap__link__box__text
        作品を見る
      .listing-wrap__link__box__img
        %i.fas.fa-seedling
%ul.pf__nav
  %li.pf__nav__works
    .pf__nav__works__text
      %i.fas.fa-desktop
      DETAIL

app/views/pft/detail2.html.haml
%ul.pf__nav
  %li.pf__nav__works
    = link_to detail2_path, class: "pf__nav__works__text" do
      %i.fas.fa-desktop
      DETAIL
%ul.pf__nav
  %li.pf__nav__works
    = link_to work_path, class: "pf__nav__works__text" do
      %i.fas.fa-desktop
      WORKS
  %li.pf__nav__principle
    = link_to contact_path, class: "pf__nav__principle__text" do
      %i.far.fa-comments
      PROFILE
.pic
  %ul.pic__slider
    %li.pic__slider__works
      =link_to "http://3.113.38.81/", class: ".pic__slider__works__path" do
        = image_tag 'chat.png', height: '400px', width: '600px'
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-project-diagram
      プログラム（プロジェクト）名
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    chat-space
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-list-ul
      プログラムの概要やビジュアル（UI）の紹介
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    メッセージ送信
    %br
    ・ユーザー同士の会話
    %br
    ・グループでの会話
    %br
    %i.far.fa-arrow-alt-circle-right
    画像の送信
    %br
    %i.far.fa-arrow-alt-circle-right
    グループ編集機能
    %br
    %i.far.fa-arrow-alt-circle-right
    ユーザー検索機能
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-user-alt
      クライアント名
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    なし
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fab.fa-product-hunt
      製作時期と製作期間
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    2019/11/6 ~ 2019/11/18
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-bullseye
      プログラムの目的
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    DB設計・フロントエンド・バックエンド・WEBデザインの知識を深めるため
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-cube
      プログラムのコンセプト
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    なし
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.far.fa-comment-dots
      クライアントの要求事項や設計仕様
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    メッセージ送信
    %br
    ・ユーザー同士の会話
    %br
    ・グループでの会話
    %br
    %i.far.fa-arrow-alt-circle-right
    画像の送信
    %br
    %i.far.fa-arrow-alt-circle-right
    グループ編集機能
    %br
    %i.far.fa-arrow-alt-circle-right
    ユーザー検索機能
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fab.fa-github
      使用言語や仕様ソフト、開発環境の紹介
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    Ruby/ Rails/ haml/ scss/ js/ jquery/ ajax/ json/ jbuilder/ mysql/ aws
%ul.detail__nav
  %li.detail__nav__works
    .detail__nav__works__text
      %i.fas.fa-arrows-alt
      チームで作成した場合は自分の担当箇所やポジションの紹介
.answer
  .answer__text
    %i.far.fa-arrow-alt-circle-right
    個人開発のため全て
.listing-wrap
  = link_to "http://3.113.38.81/", class: "listing-wrap__link" do
    .listing-wrap__link__box
      .listing-wrap__link__box__text
        作品を見る
      .listing-wrap__link__box__img
        %i.fas.fa-seedling
%ul.pf__nav
  %li.pf__nav__works
    = link_to detail2_path, class: "pf__nav__works__text" do
      %i.fas.fa-desktop
      DETAIL

app/views/pft/index.html.haml
.pf
  %ul.pf__slider
    %li.pf__slider__head
      .pf__slider__head__text
        teratti
        %br
        〜Exciting in shape〜
    -# %li.pf__slider__create
    -#   = image_tag "/assets/images/エンジニア１.jpeg", class: "pf__slider__create__img"
    -# %li.pf__slider__creativ
    -#   = image_tag "/assets/images/エンジニア２.jpeg", class: "pf__slider__creativ__img"
  %ul.pf__nav
    %li.pf__nav__works
      = link_to work_path, class: "pf__nav__works__text" do
        %i.fas.fa-desktop
        WORKS
    %li.pf__nav__principle
      = link_to contact_path, class: "pf__nav__principle__text" do
        %i.far.fa-comments
        PROFILE
  %ul.pf__body
    %li.pf__body__text1
      WEB Engineer
    %li.pf__body__text2
      創造力
    %li.pf__body__text3
      想像力

app/views/pft/work.html.haml
%ul.pf__nav
  %li.pf__nav__works
    = link_to work_path, class: "pf__nav__works__text" do
      %i.fas.fa-desktop
      WORKS
%ul.pf__nav
  %li.pf__nav__works
    = link_to root_path, class: "pf__nav__works__text" do
      %i.fas.fa-backward
      TOP
  %li.pf__nav__principle
    = link_to contact_path, class: "pf__nav__principle__text" do
      %i.far.fa-comments
      PROFILE
%ul.works
  %li.works__text
    free-market
  %li.works__text
    chat-space
.pic
  %ul.pic__slider
    %li.pic__slider__works
      =link_to detail_path, class: ".pic__slider__works__path" do
        = image_tag 'free.png', height: '400px', width: '600px'
    %li.pic__slider__works
      =link_to detail2_path, class: ".pic__slider__works__path" do
        = image_tag 'chat.png', height: '400px', width: '600px'
.small
  .small__pic
    %ul.small__pic__choice
      %li.small__pic__choice__list
        =link_to detail_path, class: ".pic__slider__works__path" do
          = image_tag 'free.png', height: '200px', width: '300px'
          .title
            free-market
      %li.small__pic__choice__list
        =link_to detail2_path, class: ".pic__slider__works__path" do
          = image_tag 'chat.png', height: '200px', width: '300px'
          .title
            chat-space
%ul.pf__nav
  %li.pf__nav__works
    = link_to work_path, class: "pf__nav__works__text" do
      %i.fas.fa-desktop
      WORKS